"""add user_profile conversations conversation_messages per database-plan

Revision ID: 8a26ae0570e8
Revises: 
Create Date: 2026-01-29 10:00:33.699183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a26ae0570e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    is_sqlite = conn.dialect.name == 'sqlite'

    if is_sqlite:
        # SQLite: idempotent DDL (IF NOT EXISTS / DROP IF EXISTS)
        op.execute('DROP TABLE IF EXISTS users')
        op.execute('''
            CREATE TABLE IF NOT EXISTS user_profile (
                _openid TEXT NOT NULL PRIMARY KEY,
                nick_name TEXT NOT NULL,
                avatar_url TEXT,
                join_time INTEGER NOT NULL,
                agent_count INTEGER DEFAULT 0,
                conversation_count INTEGER DEFAULT 0,
                updated_at INTEGER
            )
        ''')
        op.execute('''
            CREATE TABLE IF NOT EXISTS conversations (
                id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                _openid TEXT NOT NULL REFERENCES user_profile(_openid),
                chat_id TEXT NOT NULL UNIQUE,
                title TEXT NOT NULL,
                agent_ip TEXT,
                preview TEXT,
                created_at INTEGER NOT NULL,
                updated_at INTEGER NOT NULL
            )
        ''')
        op.execute('CREATE INDEX IF NOT EXISTS idx_conversations_openid_updated ON conversations(_openid, updated_at)')
        op.execute('''
            CREATE TABLE IF NOT EXISTS conversation_messages (
                id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                _openid TEXT NOT NULL,
                conversation_id TEXT NOT NULL REFERENCES conversations(chat_id),
                message_id TEXT NOT NULL UNIQUE,
                speaker TEXT NOT NULL,
                content TEXT NOT NULL,
                created_at INTEGER NOT NULL
            )
        ''')
        op.execute('CREATE INDEX IF NOT EXISTS idx_conversation_messages_conv_created ON conversation_messages(conversation_id, created_at)')
        op.execute('CREATE INDEX IF NOT EXISTS idx_conversation_messages_openid ON conversation_messages(_openid)')
    else:
        # Non-SQLite: standard Alembic ops (assume no prior new tables)
        op.create_table(
            'user_profile',
            sa.Column('_openid', sa.String(128), nullable=False),
            sa.Column('nick_name', sa.String(128), nullable=False),
            sa.Column('avatar_url', sa.String(512), nullable=True),
            sa.Column('join_time', sa.BigInteger(), nullable=False),
            sa.Column('agent_count', sa.Integer(), nullable=True, server_default=sa.text('0')),
            sa.Column('conversation_count', sa.Integer(), nullable=True, server_default=sa.text('0')),
            sa.Column('updated_at', sa.BigInteger(), nullable=True),
            sa.PrimaryKeyConstraint('_openid'),
        )
        op.create_table(
            'conversations',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('_openid', sa.String(128), sa.ForeignKey('user_profile._openid'), nullable=False),
            sa.Column('chat_id', sa.String(128), nullable=False),
            sa.Column('title', sa.String(256), nullable=False),
            sa.Column('agent_ip', sa.String(64), nullable=True),
            sa.Column('preview', sa.String(512), nullable=True),
            sa.Column('created_at', sa.BigInteger(), nullable=False),
            sa.Column('updated_at', sa.BigInteger(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('chat_id'),
        )
        op.create_index('idx_conversations_openid_updated', 'conversations', ['_openid', 'updated_at'], unique=False)
        op.create_table(
            'conversation_messages',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('_openid', sa.String(128), nullable=False),
            sa.Column('conversation_id', sa.String(128), sa.ForeignKey('conversations.chat_id'), nullable=False),
            sa.Column('message_id', sa.String(64), nullable=False),
            sa.Column('speaker', sa.String(16), nullable=False),
            sa.Column('content', sa.Text(), nullable=False),
            sa.Column('created_at', sa.BigInteger(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('message_id'),
        )
        op.create_index('idx_conversation_messages_conv_created', 'conversation_messages', ['conversation_id', 'created_at'], unique=False)
        op.create_index('idx_conversation_messages_openid', 'conversation_messages', ['_openid'], unique=False)
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_users_openid'))
            batch_op.drop_index(batch_op.f('ix_users_unionid'))
        op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate users table
    op.create_table('users',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('openid', sa.VARCHAR(length=128), nullable=False),
        sa.Column('unionid', sa.VARCHAR(length=128), nullable=True),
        sa.Column('nick_name', sa.VARCHAR(length=128), nullable=True),
        sa.Column('avatar_url', sa.VARCHAR(length=512), nullable=True),
        sa.Column('join_date', sa.DATE(), nullable=True),
        sa.Column('agent_count', sa.INTEGER(), nullable=True),
        sa.Column('conversation_count', sa.INTEGER(), nullable=True),
        sa.Column('created_at', sa.DATETIME(), nullable=True),
        sa.Column('updated_at', sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_unionid'), ['unionid'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_openid'), ['openid'], unique=1)

    # Drop new tables (reverse order due to FK)
    op.drop_index('idx_conversation_messages_openid', table_name='conversation_messages')
    op.drop_index('idx_conversation_messages_conv_created', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('idx_conversations_openid_updated', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
